name: ci

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to run '
        required: true
        default: 'master'
        type: choice
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: echo
        run : |
          source ci.sh
          echo ${{ inputs.BRANCH }}