name: ci

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to run'
        required: true
        default: 'main'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo
        run : |
          source ci.sh
          echo ${{ inputs.BRANCH }}
      
      - name: new commit on same branch
        run: |
          git config --global user.name "github bot"
          git config --global user.email "githubbot@github.com"
          touch test.txt
          echo "test" >> test.txt
          git add .
          git commit -m "add test file"
          git push origin HEAD:test2
          echo "test"
      
      - name: new commit on other branch
        run: |
          git config --global user.name "github bot"
          git config --global user.email "githubbot@github.com"
          git checkout HEAD:test1
          git merge HEAD:test2
          git push origin HEAD:test1
